import { Command } from "commander";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { readExistingWiki } from "../utils/wiki.js";
import { ClaudeAdapter } from "../adapter/index.js";

function formatTimestamp(date: Date): string {
  return date.toISOString().replace(/:/g, "-").replace(/\.\d+Z$/, "");
}

export const queryCommand = new Command("query")
  .description("Query the knowledge base")
  .argument("<question>", "Question to ask the knowledge base")
  .action(async (question: string) => {
    const kbRoot = process.cwd();

    // 1. Read wiki pages
    const wikiPages = await readExistingWiki(kbRoot);

    if (wikiPages.length === 0) {
      console.error("No wiki content yet. Run `kb compile` first.");
      process.exitCode = 1;
      return;
    }

    // 2. Call adapter
    const adapter = new ClaudeAdapter();
    let result;
    try {
      result = await adapter.answerQuery(question, wikiPages);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(`Query failed: ${message}`);
      process.exitCode = 1;
      return;
    }

    // 3. Write output
    const now = new Date();
    const timestamp = formatTimestamp(now);
    const filename = `${timestamp}-query.md`;
    const outputsDir = join(kbRoot, "outputs");
    await mkdir(outputsDir, { recursive: true });

    const outputPath = join(outputsDir, filename);
    const output = `# Query: ${question}

${result.answer}

---
*Generated by kb on ${now.toISOString()}*
*Sources consulted: ${result.sources.join(", ")}*
`;

    await writeFile(outputPath, output, "utf-8");

    // 4. Print path
    console.log(outputPath);
  });
