import { Command } from "commander";
import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { answerQuery } from "../adapter/index.js";
import type { WikiContent } from "../adapter/index.js";

const WIKI_DIR = "wiki";
const OUTPUT_DIR = "outputs";
const EXCLUDED_FILES = new Set(["INDEX.md", "LOG.md"]);

async function getWikiPages(): Promise<WikiContent[]> {
  const files = await readdir(WIKI_DIR);
  const wikiFiles = files.filter(
    (f) => f.endsWith(".md") && !EXCLUDED_FILES.has(f),
  );

  const pages: WikiContent[] = [];
  for (const file of wikiFiles) {
    const filePath = join(WIKI_DIR, file);
    const content = await readFile(filePath, "utf-8");
    pages.push({ path: filePath, content });
  }

  return pages;
}

function formatTimestamp(date: Date): string {
  return date.toISOString().replace(/:/g, "-").replace(/\.\d+Z$/, "");
}

function formatOutput(
  question: string,
  answer: string,
  sources: string[],
  timestamp: string,
): string {
  return `# Query: ${question}

${answer}

---
*Generated by kb on ${timestamp}*
*Sources consulted: ${sources.join(", ")}*
`;
}

export async function runQuery(question: string): Promise<string> {
  // Read wiki pages
  const wikiPages = await getWikiPages();

  if (wikiPages.length === 0) {
    throw new Error(
      "No wiki content yet. Run `kb compile` first.",
    );
  }

  // Call adapter
  const result = await answerQuery(question, wikiPages);

  // Write output
  const now = new Date();
  const timestamp = formatTimestamp(now);
  const filename = `${timestamp}-query.md`;
  const outputPath = join(OUTPUT_DIR, filename);

  await mkdir(OUTPUT_DIR, { recursive: true });
  const output = formatOutput(
    question,
    result.answer,
    result.sources,
    now.toISOString(),
  );
  await writeFile(outputPath, output, "utf-8");

  return outputPath;
}

export const queryCommand = new Command("query")
  .description("Query the knowledge base")
  .argument("<question>", "Question to ask the knowledge base")
  .action(async (question: string) => {
    try {
      const outputPath = await runQuery(question);
      console.log(outputPath);
    } catch (err) {
      if (
        err instanceof Error &&
        err.message.includes("No wiki content yet")
      ) {
        console.error(err.message);
      } else {
        console.error(
          "Error querying knowledge base:",
          err instanceof Error ? err.message : String(err),
        );
      }
      process.exit(1);
    }
  });
