import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import { runQuery } from "../commands/query.js";

vi.mock("node:fs/promises");
vi.mock("../adapter/index.js", () => ({
  answerQuery: vi.fn().mockResolvedValue({
    answer: "The answer is 42.",
    sources: ["wiki/topic-a.md", "wiki/topic-b.md"],
    confidence: 1,
  }),
}));

const mockReaddir = vi.mocked(readdir);
const mockReadFile = vi.mocked(readFile);
const mockMkdir = vi.mocked(mkdir);
const mockWriteFile = vi.mocked(writeFile);

describe("query command", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockMkdir.mockResolvedValue(undefined);
    mockWriteFile.mockResolvedValue(undefined);
  });

  it("throws when wiki has no content pages", async () => {
    mockReaddir.mockResolvedValue(["INDEX.md", "LOG.md"] as any);

    await expect(runQuery("What is kb?")).rejects.toThrow(
      "No wiki content yet. Run `kb compile` first.",
    );
  });

  it("throws when wiki directory only has INDEX.md", async () => {
    mockReaddir.mockResolvedValue(["INDEX.md"] as any);

    await expect(runQuery("test question")).rejects.toThrow(
      "No wiki content yet",
    );
  });

  it("generates output file with correct format", async () => {
    mockReaddir.mockResolvedValue([
      "INDEX.md",
      "LOG.md",
      "topic-a.md",
      "topic-b.md",
    ] as any);
    mockReadFile.mockResolvedValue("# Topic content");

    const outputPath = await runQuery("What is the meaning of life?");

    expect(outputPath).toMatch(/^outputs\/.*-query\.md$/);
    expect(mockMkdir).toHaveBeenCalledWith("outputs", { recursive: true });
    expect(mockWriteFile).toHaveBeenCalledTimes(1);

    const writtenContent = mockWriteFile.mock.calls[0][1] as string;
    expect(writtenContent).toContain("# Query: What is the meaning of life?");
    expect(writtenContent).toContain("The answer is 42.");
    expect(writtenContent).toContain("Generated by kb on");
    expect(writtenContent).toContain(
      "Sources consulted: wiki/topic-a.md, wiki/topic-b.md",
    );
  });

  it("reads all non-excluded wiki files", async () => {
    mockReaddir.mockResolvedValue([
      "INDEX.md",
      "LOG.md",
      "topic-a.md",
      "topic-b.md",
      "topic-c.md",
    ] as any);
    mockReadFile.mockResolvedValue("content");

    await runQuery("test");

    // Should read topic-a, topic-b, topic-c (not INDEX.md or LOG.md)
    expect(mockReadFile).toHaveBeenCalledTimes(3);
    expect(mockReadFile).toHaveBeenCalledWith("wiki/topic-a.md", "utf-8");
    expect(mockReadFile).toHaveBeenCalledWith("wiki/topic-b.md", "utf-8");
    expect(mockReadFile).toHaveBeenCalledWith("wiki/topic-c.md", "utf-8");
  });

  it("output filename contains timestamp", async () => {
    mockReaddir.mockResolvedValue(["topic-a.md"] as any);
    mockReadFile.mockResolvedValue("content");

    const outputPath = await runQuery("test");

    // Should match pattern like outputs/2024-01-15T10-30-00-query.md
    expect(outputPath).toMatch(
      /^outputs\/\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}-query\.md$/,
    );
  });
});
